name: search/kcolor/5
seed: 1

log_level: info
report_interval: 10
eval_interval: 50
save_interval: 50

mlp_arch:
  hidden_sizes: [32]
  activation: ReLU

data_path: data/kcolor
train_sets:
  - name: 3-5-0.5
    samples: 2000
    max_tries: 5
    max_flips: 50
    iterations: 10000

eval_set:
  name: 3-10-0.5
  samples: 10
  max_tries: 10
  max_flips: 200

model_path: False
data_shuffle: False
eval_multi: True

gnn_hidden_size: 32
readout_hidden_size: 64
gnn_iter: 2
gnn_async: False

cycles: 1
optimizer: RMSprop
lr: 0.0005
lr_milestones: [200, 500, 1000, 5000]
lr_decay: 0.5

method: reinforce
discount: 0.25
walk_prob: 0.5
